services:
  inventory-service:
    image: postgres:15  # Sử dụng hình ảnh PostgreSQL
    container_name: inventory-service
    environment:
      POSTGRES_USER: postgres  # Người dùng PostgreSQL cho inventory
      POSTGRES_PASSWORD: postgres  # Mật khẩu PostgreSQL cho inventory
      POSTGRES_DB: inventory_db  # Tên cơ sở dữ liệu mặc định cho inventory
    ports:
      - "5431:5432"  # Ánh xạ cổng 5431 trên host tới cổng 5432 trong container
    volumes:
      - inventory_data:/var/lib/postgresql/data  # Lưu trữ dữ liệu bền vững cho inventory
  order-service:
    image: postgres:15  # Sử dụng hình ảnh PostgreSQL
    container_name: order-service
    environment:
      POSTGRES_USER: postgres  # Người dùng PostgreSQL cho order
      POSTGRES_PASSWORD: postgres  # Mật khẩu PostgreSQL cho order
      POSTGRES_DB: order_db  # Tên cơ sở dữ liệu mặc định cho order
    ports:
      - "5430:5432"  # Ánh xạ cổng 5430 trên host tới cổng 5432 trong container
    volumes:
      - order_data:/var/lib/postgresql/data  # Lưu trữ dữ liệu bền vững cho order
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6
    ports:
      - "8181:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
volumes:
  inventory_data:
  order_data: