spring :
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5431/inventory_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
  instance:
    hostname: localhost
management:
  tracing:
    sampling:
      probability: 1.0
